This is my analyzer after class on 5/6/20 after Elbert cleaned the data through the new scraper

In [1]:
# import pandas
import pandas as pd

In [2]:
# read csv in
df = pd.read_csv('../data/WARN_05072020.csv')
df

,notice_date,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,5/4/2020,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of The Rox...","2 Avenue of the Americas New York, NY 10013",New York County,(201) 272-5800,Hotel,79,79,5/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
1,5/5/2020,Plant Closing,RR Donnelley (TuckerPrinters facility),"270 Middle Rd. Henrietta, NY 14467",Monroe County,(716) 564-6469,Commercial Printing,33,33,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Closing
2,4/28/2020,Plant Layoff,TripAdvisor LLC,"17 Battery Place New York, NY 10004",New York County,(781) 800-5341,American online travel company,36,36,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
3,4/15/2020,Temporary Plant Layoff,"PBM, LLC (Perfect Building Maintenance)","405 Lexington Avenue, 40th Floor New York, NY ...",New York County,(212) 244-3434,Building maintenance and cleaning services,349,NaN,3/9/2020,Unforeseeable business circumstances prompted ...,Local 32BJ SEIU,Temporary Plant Layoff
4,5/4/2020,Temporary Plant Layoff,"NRG Energy, Inc. (Green Mountain Energy NYC Of...","16 Madison Square Park West, 12th Floor New Yo...",New York County,(713) 537-2187,Renewable Energy Provider,71,NaN,Beginning,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,1/6/2020,Plant Closing,Macy's Broadway Mall Store (Macy's Retail Hold...,"100 Broadway Mall Hicksville, NY 11801",Nassau County,(646) 429-7462,Retail Store,155,155,Macy's,Economic,The employees are not represented by a union.,Plant Closing
1294,12/27/2019,Temporary Plant Closing,Wesley Gardens Nursing Home,"3 Upton Park Rochester, NY 14607",Monroe County,(585) 241-2105,Nursing Home,132,132,Beginning,Due to a water line break,1199 SEIU,Temporary Plant Closing
1295,12/30/2019,Plant Closing,"127 W. 43rd St. Chophouse, Inc. (Heartland Bre...","127 West 43rd Street New York, NY 10018",New York County,(917) 999-6532,Restaurant,106,106,The,Economic,The employees are not represented by a union.,Plant Closing
1296,12/30/2019,Plant Closing,"New York Express and Logistics, LLC","292 Wolf Road Latham, NY 12110",Albany County,(617) 968-5311,Trucking company providing freight transportat...,48,48,3/31/2020,Contract between New York Express and Logistic...,The employees are not represented by a union.,Plant Closing
1297,12/23/2019,Plant Closing,"Benchmark Hospitality of Westchester, LLC (Dor...","975 Anderson Hill Road Rye Brook, NY 10573",Westchester County,(914) 935-6652,Resort Hotel,275,275,1/12/2020,Loss of funding,The employees are not represented by a union.,Plant Closing

In [3]:
# Dataset from 01/01/20 - 05/07/20 
# For updated totals, please use 'scrape-all-years.ipynb' in this folder to create/import new CSV
df.head()

,notice_date,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,5/4/2020,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of The Rox...","2 Avenue of the Americas New York, NY 10013",New York County,(201) 272-5800,Hotel,79,79,5/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
1,5/5/2020,Plant Closing,RR Donnelley (TuckerPrinters facility),"270 Middle Rd. Henrietta, NY 14467",Monroe County,(716) 564-6469,Commercial Printing,33,33,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Closing
2,4/28/2020,Plant Layoff,TripAdvisor LLC,"17 Battery Place New York, NY 10004",New York County,(781) 800-5341,American online travel company,36,36,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
3,4/15/2020,Temporary Plant Layoff,"PBM, LLC (Perfect Building Maintenance)","405 Lexington Avenue, 40th Floor New York, NY ...",New York County,(212) 244-3434,Building maintenance and cleaning services,349,NaN,3/9/2020,Unforeseeable business circumstances prompted ...,Local 32BJ SEIU,Temporary Plant Layoff
4,5/4/2020,Temporary Plant Layoff,"NRG Energy, Inc. (Green Mountain Energy NYC Of...","16 Madison Square Park West, 12th Floor New Yo...",New York County,(713) 537-2187,Renewable Energy Provider,71,NaN,Beginning,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff

In [4]:
# reveal each column header
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1298 non-null   object
 1   reason           1298 non-null   object
 2   company          1298 non-null   object
 3   address          1297 non-null   object
 4   county           1298 non-null   object
 5   phone            1298 non-null   object
 6   business_type    1298 non-null   object
 7   affected         1218 non-null   object
 8   total_employees  527 non-null    object
 9   layoff_date      1295 non-null   object
 10  dislocation      1298 non-null   object
 11  union            1298 non-null   object
 12  classification   1298 non-null   object
dtypes: object(13)
memory usage: 132.0+ KB

In [5]:
# Fill all null values with 0 and clean all non-perfect integers in 'affected' column
df = df.fillna(0)
df.affected[df.affected == 'To'] = 0
df.affected[df.affected == '1,004'] = 1004
df.affected[df.affected == '1,166'] = 1166
df.affected[df.affected == '(62'] = 62
df.affected[df.affected == '1,321'] = 1321

In [6]:
# Clean total_employees section
df.total_employees[df.total_employees == '----'] = 0

In [7]:
# Change 'affected' and 'total_employees' section from string objects to integers 
df['affected'] = df['affected'].astype(int)
df['total_employees'] = df['total_employees'].astype(int)

In [8]:
# Check to make sure changes are correct
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1298 non-null   object
 1   reason           1298 non-null   object
 2   company          1298 non-null   object
 3   address          1298 non-null   object
 4   county           1298 non-null   object
 5   phone            1298 non-null   object
 6   business_type    1298 non-null   object
 7   affected         1298 non-null   int64
 8   total_employees  1298 non-null   int64
 9   layoff_date      1298 non-null   object
 10  dislocation      1298 non-null   object
 11  union            1298 non-null   object
 12  classification   1298 non-null   object
dtypes: int64(2), object(11)
memory usage: 132.0+ KB

In [9]:
df['affected'] = pd.to_numeric(df['affected'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   notice_date      1298 non-null   object
 1   reason           1298 non-null   object
 2   company          1298 non-null   object
 3   address          1298 non-null   object
 4   county           1298 non-null   object
 5   phone            1298 non-null   object
 6   business_type    1298 non-null   object
 7   affected         1298 non-null   int64
 8   total_employees  1298 non-null   int64
 9   layoff_date      1298 non-null   object
 10  dislocation      1298 non-null   object
 11  union            1298 non-null   object
 12  classification   1298 non-null   object
dtypes: int64(2), object(11)
memory usage: 132.0+ KB

In [10]:
df.head()

,notice_date,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,5/4/2020,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of The Rox...","2 Avenue of the Americas New York, NY 10013",New York County,(201) 272-5800,Hotel,79,79,5/15/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Closing
1,5/5/2020,Plant Closing,RR Donnelley (TuckerPrinters facility),"270 Middle Rd. Henrietta, NY 14467",Monroe County,(716) 564-6469,Commercial Printing,33,33,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Closing
2,4/28/2020,Plant Layoff,TripAdvisor LLC,"17 Battery Place New York, NY 10004",New York County,(781) 800-5341,American online travel company,36,36,5/5/2020,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Plant Layoff
3,4/15/2020,Temporary Plant Layoff,"PBM, LLC (Perfect Building Maintenance)","405 Lexington Avenue, 40th Floor New York, NY ...",New York County,(212) 244-3434,Building maintenance and cleaning services,349,0,3/9/2020,Unforeseeable business circumstances prompted ...,Local 32BJ SEIU,Temporary Plant Layoff
4,5/4/2020,Temporary Plant Layoff,"NRG Energy, Inc. (Green Mountain Energy NYC Of...","16 Madison Square Park West, 12th Floor New Yo...",New York County,(713) 537-2187,Renewable Energy Provider,71,0,Beginning,Unforeseeable business circumstances prompted ...,The employees are not represented by a union.,Temporary Plant Layoff

In [11]:
# Find out the type of businesses that were affected the most
df['business_type'].value_counts().reset_index()

                                     index  business_type
0                               Restaurant            494
1                                    Hotel            147
2                                   Retail             43
3                          Auto Dealership             24
4                                 Catering             16
..                                     ...            ...
356               Refrigeration Wholesaler              1
357            Watch, Guard, Patrol Agency              1
358                      Interior designer              1
359                             Broth Shop              1
360  Waste Services and Material Recycling              1

[361 rows x 2 columns]

In [12]:
# Find out the reasons why
df['dislocation'].value_counts()

Unforeseeable business circumstances prompted by COVID-19                                                                                                                                                                                                                                                                                                1145
Economic                                                                                                                                                                                                                                                                                                                                                   70
Unforeseeable  business circumstances prompted by COVID-19                                                                                                                                                                                                                                                                                                  9
Sale of Business                                                                                                                                                                                                                                                                                                                                            3
The Companyâ€™s initial temporary layoffs were unforeseeable due to the impacts of COVID-19. The Companyâ€™s permanent layoffs and cessation of operations were due to Unforeseeable Business Circumstances in that the Companyâ€™s customers breached their Transportation Contracts by refusing to pay amounts due through the end of the school year.          3
Unforeseen business circumstances as a result of the COVID-19 virus                                                                                                                                                                                                                                                                                         3
Restructuring which will involve the relocation of certain operations from Crosstexâ€™s Long Island location to Rush, NY.                                                                                                                                                                                                                                     3
Economic and unforeseen business circumstances as a result of COVID-19                                                                                                                                                                                                                                                                                      2
Winding down its in-store operations across Fairway Market stores in light of the retailer's recent bankruptcy filing and potential store closures.                                                                                                                                                                                                         2
Reduction in workload due to a change in business priorities.                                                                                                                                                                                                                                                                                               2
The contract between Swissport and the Port Authority of New York and New Jersey expires on May 1, 2020.                                                                                                                                                                                                                                                    2
Loss of funding                                                                                                                                                                                                                                                                                                                                             2
Expiration of building lease                                                                                                                                                                                                                                                                                                                                2
Sale of the business to a buyer who is relocating overseas and for economic reasons.                                                                                                                                                                                                                                                                        2
Budgetary Deficit                                                                                                                                                                                                                                                                                                                                           2
Acquisition by Community Bank                                                                                                                                                                                                                                                                                                                               2
Expiration of lease                                                                                                                                                                                                                                                                                                                                         2
EconomicUnforeseeable business circumstances prompted by COVID-19                                                                                                                                                                                                                                                                                           2
Sale of the business                                                                                                                                                                                                                                                                                                                                        1
Merger with Troutman Sanders and to become known as Troutman Pepper.                                                                                                                                                                                                                                                                                        1
Sale of business to Republic Services                                                                                                                                                                                                                                                                                                                       1
The production work is moving to another company facility in Rockaway, New Jersey.                                                                                                                                                                                                                                                                          1
Relocation                                                                                                                                                                                                                                                                                                                                                  1
Loss of Contract                                                                                                                                                                                                                                                                                                                                            1
Due to an operational change to optimize the ReadyRefresh delivery process                                                                                                                                                                                                                                                                                  1
Landlord's decision to cease operating the parking facility                                                                                                                                                                                                                                                                                                 1
Contract Loss                                                                                                                                                                                                                                                                                                                                               1
Consolidation of revenue cycle functions/closure of the Revenue Excellence Department                                                                                                                                                                                                                                                                       1
Newspaper production will be consolidated to the companyâ€™s Rochester, NY facility.                                                                                                                                                                                                                                                                          1
To be Determined                                                                                                                                                                                                                                                                                                                                            1
School closing mandated by the State of New York due to the unforeseeable business circumstances prompted by COVID-19                                                                                                                                                                                                                                       1
Economic and stricter new State air emission regulations designed to eliminate coal generation in New York.                                                                                                                                                                                                                                                 1
The MTA did not renew contract which expires May 31, 2020.                                                                                                                                                                                                                                                                                                  1
Discontinuation of operations                                                                                                                                                                                                                                                                                                                               1
Due to a water line break                                                                                                                                                                                                                                                                                                                                   1
Sale of Company                                                                                                                                                                                                                                                                                                                                             1
They are integrating many of these incubated brands as private brands within Walmart.                                                                                                                                                                                                                                                                       1
Death of Company President and Unforeseeable business circumstances prompted by COVID-19                                                                                                                                                                                                                                                                    1
Sale of heritage Dresser-Rand / SGT Government business products portfolio to Curtiss-Wright.                                                                                                                                                                                                                                                               1
Catholic Guardian Services has decided to discontinue operation of its Community Habilitation program in the New York City area for persons with development disabilities.                                                                                                                                                                                  1
Loss of Contract with New York Transit Authority                                                                                                                                                                                                                                                                                                            1
Relocation to Colorado                                                                                                                                                                                                                                                                                                                                      1
Due to a substantial loss of contract funding for their Preventive program.                                                                                                                                                                                                                                                                                 1
Reorganization                                                                                                                                                                                                                                                                                                                                              1
GNYHA Management Corporation has announced the planned sale of its Acurity, Inc. and Nexera, Inc. businesses to Premier Inc.                                                                                                                                                                                                                                1
Early contract termination by Maersk Lines. They are moving their three vessel services calling at GCT New York to APM Terminal in Elizabeth, NJ.                                                                                                                                                                                                           1
Sale of business                                                                                                                                                                                                                                                                                                                                            1
The decision was made to integrate conversational commerce into Walmart.                                                                                                                                                                                                                                                                                    1
Company Reorganization                                                                                                                                                                                                                                                                                                                                      1
Contract termination by Metropolitan Transit Authority                                                                                                                                                                                                                                                                                                      1
Relocating facility to Minnesota.                                                                                                                                                                                                                                                                                                                           1
Relocation of Corporate Headquarters to Nashville, TN                                                                                                                                                                                                                                                                                                       1
Unforeseen business circumstances as a result of COVID-19                                                                                                                                                                                                                                                                                                   1
Maria Russo, Human Resources Director                                                                                                                                                                                                                                                                                                                       1
The Companyâ€™s initial temporary layoffs were unforeseeable due to the impacts of COVID-19 and the Companyâ€™s permanent layoffs and cessation of operations were due to Unforeseeable Business Circumstances in that the Companyâ€™s customers breached their Transportation Contracts by refusing to pay amounts due through the end of the school year.       1
GNYHA Management Corporation has announced the planned sale of its  Acurity, Inc. and Nexera, Inc. businesses to Premier Inc.                                                                                                                                                                                                                               1
Restructure of the New York Metro market                                                                                                                                                                                                                                                                                                                    1

In [13]:
# Clean all Covid-19 related reasons into one group
df.loc[df['dislocation'].str.contains('COVID-19'), 'dislocation'] = 'COVID-19'
dislocation = df['dislocation'].value_counts().reset_index().rename(columns={'index': 'dislocation', 'dislocation': 'count'})
dislocation

                                          dislocation  count
0                                            COVID-19   1168
1                                            Economic     70
2                                    Sale of Business      3
3   Restructuring which will involve the relocatio...      3
4                                 Expiration of lease      2
5   The contract between Swissport and the Port Au...      2
6                        Expiration of building lease      2
7   Sale of the business to a buyer who is relocat...      2
8                                   Budgetary Deficit      2
9   Reduction in workload due to a change in busin...      2
10                      Acquisition by Community Bank      2
11                                    Loss of funding      2
12  Winding down its in-store operations across Fa...      2
13  Landlord's decision to cease operating the par...      1
14  Due to an operational change to optimize the R...      1
15  GNYHA Management Corporation has announced the...      1
16                                   To be Determined      1
17  The production work is moving to another compa...      1
18  Economic and stricter new State air emission r...      1
19              Sale of business to Republic Services      1
20  Merger with Troutman Sanders and to become kno...      1
21                      Discontinuation of operations      1
22  They are integrating many of these incubated b...      1
23                               Sale of the business      1
24  Catholic Guardian Services has decided to disc...      1
25                          Due to a water line break      1
26                                    Sale of Company      1
27                                   Loss of Contract      1
28                  Relocating facility to Minnesota.      1
29              Maria Russo, Human Resources Director      1
30  The MTA did not renew contract which expires M...      1
31  Newspaper production will be consolidated to t...      1
32                                      Contract Loss      1
33                                         Relocation      1
34           Restructure of the New York Metro market      1
35                             Company Reorganization      1
36  Early contract termination by Maersk Lines. Th...      1
37  Due to a substantial loss of contract funding ...      1
38                             Relocation to Colorado      1
39  Consolidation of revenue cycle functions/closu...      1
40  Sale of heritage Dresser-Rand / SGT Government...      1
41   Loss of Contract with New York Transit Authority      1
42                                     Reorganization      1
43  GNYHA Management Corporation has announced the...      1
44                                   Sale of business      1
45  The decision was made to integrate conversatio...      1
46  Contract termination by Metropolitan Transit A...      1
47  Contract between New York Express and Logistic...      1
48  Relocation of Corporate Headquarters to Nashvi...      1

In [14]:
df['affected'].sum()

119024

In [15]:
# Make new list an target only businesses affected by COVID-19
covid_dislocation = "COVID-19"

In [16]:
covid_list = df[df.dislocation == covid_dislocation]

In [17]:
covid_list

,notice_date,reason,company,address,county,phone,business_type,affected,total_employees,layoff_date,dislocation,union,classification
0,5/4/2020,Temporary Plant Closing,"Hartz Hotel Services, Inc. (manager of The Rox...","2 Avenue of the Americas New York, NY 10013",New York County,(201) 272-5800,Hotel,79,79,5/15/2020,COVID-19,The employees are not represented by a union.,Temporary Plant Closing
1,5/5/2020,Plant Closing,RR Donnelley (TuckerPrinters facility),"270 Middle Rd. Henrietta, NY 14467",Monroe County,(716) 564-6469,Commercial Printing,33,33,5/5/2020,COVID-19,The employees are not represented by a union.,Plant Closing
2,4/28/2020,Plant Layoff,TripAdvisor LLC,"17 Battery Place New York, NY 10004",New York County,(781) 800-5341,American online travel company,36,36,5/5/2020,COVID-19,The employees are not represented by a union.,Plant Layoff
3,4/15/2020,Temporary Plant Layoff,"PBM, LLC (Perfect Building Maintenance)","405 Lexington Avenue, 40th Floor New York, NY ...",New York County,(212) 244-3434,Building maintenance and cleaning services,349,0,3/9/2020,COVID-19,Local 32BJ SEIU,Temporary Plant Layoff
4,5/4/2020,Temporary Plant Layoff,"NRG Energy, Inc. (Green Mountain Energy NYC Of...","16 Madison Square Park West, 12th Floor New Yo...",New York County,(713) 537-2187,Renewable Energy Provider,71,0,Beginning,COVID-19,The employees are not represented by a union.,Temporary Plant Layoff
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218,3/17/2020,Temporary Plant Closing,100 Hospitality LLC,"100 Walt Whitman Road Huntington, NY 11746",Suffolk County,(516) 627- 0021,Restaurant,68,0,3/17/2020,COVID-19,The employees are not represented by a union.,Temporary Plant Closing
1219,3/13/2020,Temporary Plant Layoff,"US Inflight Catering LLC (""dnata"")","45 Rason Road Inwood, NY 11516",Nassau County,(347) 996-8430,Catering business,73,0,3/16/2020,COVID-19,"Local Union 514, Brotherhood of Amalgamated Tr...",Temporary Plant Layoff
1220,3/12/2020,Temporary Plant Layoff,"DO & CO New York Catering, Inc.","149-32 132nd Street Jamaica, NY 11430",Queens County,(718) 529- 4570,Catering,744,744,3/19/2020,COVID-19,"United Food and Catering Workers (UFCW) Union,...",Temporary Plant Layoff
1221,3/17/2020,Temporary Plant Layoff,East Meadow Restaurant Corp.,"284 East Meadow Avenue East Meadow, NY 11554",Nassau County,(516) 627- 0021,Restaurant,30,0,3/17/2020,COVID-19,The employees are not represented by a union.,Temporary Plant Layoff
1222,3/5/2020,Plant Closing,"Modell's II, Inc.",(Modell's Sporting Goods) Support Center 498 ...,New York County,(212) 822-1002,Restaurant,30,0,3/17/2020,COVID-19,"Local 1102 Retail, Wholesale and Department ...",Plant Closing

In [18]:
# export dataset to CSV.
covid_list.to_csv('../output/WARN_COVID_05072020.csv', index=False)

In [20]:
# Discover how many people were issued WARN notices due to COVID-19 by business type/industry. Search for top 20 with .head() code.
affected_industries = covid_list.groupby(['business_type'])['affected'].agg('sum').sort_values(ascending = False).reset_index()
affected_industries

                         business_type  affected
0                           Restaurant     42174
1                                Hotel     15718
2                             Catering      3217
3                Retail clothing store      2696
4                               Retail      2604
..                                 ...       ...
277                  Food Distribution         0
278                    Furniture Store         0
279                             Museum         0
280          Obstetrics and Gynecology         0
281  Physical and Occupational Therapy         0

[282 rows x 2 columns]

In [21]:
# export dataset to CSV.
affected_industries.to_csv('../output/Total_COVID_Affected_by_industry.csv', index=False)

In [19]:
#which comapnies lost the most people due to COVID. Search top 20.
covid_list.groupby(['company'])['affected'].agg('sum').sort_values(ascending = False).reset_index().head(20)

                                              company  affected
0   Abercrombie & Fitch, abercrombie kids, Hollist...      2696
1   OS Restaurant Services, LLC (Bloomin Brands - ...      2478
2   American Sales Management Organization LLC dba...      1321
3                                       Regal Cinemas      1004
4                                Hudson's Bay Company       998
5                                            Zara USA       918
6                             OTG JFK T5 Venture, LLC       916
7                 Mid Rockland Imaging Partners, Inc.       894
8    Icon Parking Holdings LLC (227 Locations in NYC)       883
9                                      Acme Bus Corp.       814
10         Yeled v'Yalda Early Childhood Center, Inc.       762
11                    DO & CO New York Catering, Inc.       744
12                     Akwesasne Mohawk Casino Resort       700
13                                 Maison Kayser, LLC       689
14              Feast American Diners, LLC dba Dennys       683
15   88 Ninth Avenue Hospitality, LLC dba Catch Steak       683
16  PQ New York Inc. dba Le Pain Quotidien (29 New...       678
17                    Scott's Peak n' Peek Resort LLC       669
18  Crest Hollow Country Club dba Crest Hollow Clu...       598
19                                          Yelp Inc.       590

In [95]:
# Next, track amount of people affected by COVID-19 WARN notices by date
covid_affected = covid_list.groupby(['notice_date'])['affected'].agg('sum').sort_values(ascending = False).reset_index()
covid_affected

               notice_date  affected
0                3/25/2020      7604
1                3/18/2020      6783
2                3/31/2020      6398
3                3/23/2020      6183
4                3/19/2020      6154
5                3/26/2020      5276
6                3/30/2020      5065
7                3/20/2020      4999
8                3/27/2020      4835
9                3/16/2020      4376
10                4/2/2020      3939
11                4/8/2020      3862
12               3/24/2020      3742
13               4/10/2020      3670
14               4/27/2020      2839
15               3/17/2020      2609
16               4/17/2020      2497
17                4/1/2020      2485
18                4/6/2020      2333
19                4/3/2020      2091
20               4/28/2020      1941
21               4/29/2020      1695
22               4/13/2020      1416
23               4/16/2020      1298
24               3/22/2020      1256
25               4/30/2020      1228
26                4/9/2020      1204
27               4/21/2020      1115
28                4/7/2020      1031
29                5/1/2020      1026
30               4/23/2020      1018
31               4/22/2020       989
32               4/15/2020       915
33               3/21/2020       889
34               4/14/2020       782
35               3/15/2020       776
36               3/12/2020       744
37               3/29/2020       615
38               4/20/2020       456
39                5/4/2020       384
40               4/24/2020       294
41               3/14/2020       258
42               4/18/2020       204
43               3/13/2020       177
44  3/31/2020 and 4/6/2020       119
45               3/28/2020        80
46                5/5/2020        33
47                3/5/2020        30
48                3/3/2020        26

In [96]:
# export dataset to CSV.
covid_affected.to_csv('../output/Total_COVID_Affected_by_date.csv', index=False)

In [78]:
# The amount of WARN notices filed by date due to COVID
pd.set_option('display.max_rows', 50)
date = covid_list['notice_date'].value_counts().reset_index().rename(columns = {'index': 'date', 'notice_date': 'count'})
date = date[~date['date'].str.contains('2019')]
date

                      date  count
0                3/31/2020     73
1                3/25/2020     70
2                3/23/2020     68
3                3/20/2020     68
4                3/27/2020     68
5                3/19/2020     58
6                3/30/2020     55
7                3/18/2020     55
8                3/26/2020     51
9                3/16/2020     45
10               4/17/2020     44
11               3/24/2020     43
12                4/3/2020     41
13                4/8/2020     41
14                4/2/2020     39
15               3/17/2020     38
16                4/6/2020     33
17               4/10/2020     26
18                4/1/2020     23
19               4/13/2020     20
20                4/7/2020     20
21               4/22/2020     17
22               4/14/2020     15
23               4/16/2020     13
24               4/18/2020     12
25               3/21/2020     12
26               4/28/2020     11
27                4/9/2020     10
28               4/15/2020     10
29               4/27/2020     10
30               3/15/2020     10
31               3/29/2020      8
32               4/23/2020      7
33               4/21/2020      7
34               4/20/2020      7
35               3/22/2020      6
36               4/29/2020      6
37               4/30/2020      5
38                5/4/2020      4
39               3/13/2020      3
40               4/24/2020      3
41                5/1/2020      3
42               3/14/2020      3
43               3/28/2020      2
44                3/5/2020      1
45               3/12/2020      1
46  3/31/2020 and 4/6/2020      1
47                3/3/2020      1
48                5/5/2020      1

In [89]:
# Now just track how many WARN notices there were for the entire year from Jan. 1 2020 no matter the reason.
df.groupby(['notice_date'])['affected'].agg('sum').sort_values(ascending = False).reset_index()

   notice_date  affected
0    3/25/2020      7691
1    3/18/2020      7006
2    3/31/2020      6398
3    3/23/2020      6183
4    3/19/2020      6170
..         ...       ...
90  10/16/2019        12
91   11/4/2019         2
92    3/2/2020         2
93    3/6/2020         2
94   1/17/2020         1

[95 rows x 2 columns]

In [93]:
pd.set_option('display.max_rows', 86)
date = df['notice_date'].value_counts().reset_index().rename(columns = {'index': 'date', 'notice_date': 'count'})
date = date[~date['date'].str.contains('2019')]
date

                                 date  count
0                           3/31/2020     73
1                           3/27/2020     71
2                           3/25/2020     71
3                           3/23/2020     68
4                           3/20/2020     68
5                           3/19/2020     59
6                           3/18/2020     57
7                           3/30/2020     56
8                           3/26/2020     53
9                           3/16/2020     47
10                          4/17/2020     45
11                          3/24/2020     44
12                           4/3/2020     43
13                           4/8/2020     42
14                          3/17/2020     39
15                           4/2/2020     39
16                           4/6/2020     34
17                           4/1/2020     26
18                          4/10/2020     26
19                           4/7/2020     20
20                          4/13/2020     20
21                          4/22/2020     17
22                          4/14/2020     15
23                          4/16/2020     13
24                          3/21/2020     12
25                          4/18/2020     12
26                          4/27/2020     12
27                          4/15/2020     11
28                          4/28/2020     11
29                           4/9/2020     10
30                          3/15/2020     10
31                          4/21/2020      9
32                          3/29/2020      8
33                          4/20/2020      7
34                          4/23/2020      7
35                          1/24/2020      6
36                           2/4/2020      6
37                          4/29/2020      6
38                          4/30/2020      6
39                          3/22/2020      6
40                           5/4/2020      4
41                           2/6/2020      4
42                          2/28/2020      4
43                          1/15/2020      4
44                          3/14/2020      4
45                          3/13/2020      4
46                          4/24/2020      4
47                           1/7/2020      4
48                          1/31/2020      3
49                           5/1/2020      3
50                          1/23/2020      3
51                          1/21/2020      3
52                          2/19/2020      3
53                          2/13/2020      3
54                          2/12/2020      3
55                          1/30/2020      3
56                          1/13/2020      3
57                          2/27/2020      3
58                           3/5/2020      2
60                          3/28/2020      2
61                           3/3/2020      2
62                          3/12/2020      2
64                           2/7/2020      2
66                           1/3/2020      2
67                          7/13/2018      2
69                          3/11/2020      2
70                           3/4/2020      2
74                          2/20/2020      1
76                          1/29/2020      1
77                           3/6/2020      1
78                          3/10/2020      1
79                          2/11/2020      1
80                           3/2/2020      1
81                          2/24/2020      1
82             3/31/2020 and 4/6/2020      1
83                          1/12/2020      1
84   3/27/2020 3/30/2020 and 4/8/2020      1
85                           5/5/2020      1
86                          1/17/2020      1
87                          1/16/2020      1
88                           1/6/2020      1
89                          1/14/2020      1
91                          2/26/2020      1
92                           1/8/2020      1
93  1/10/2020 1/15/2020 and 1/21/2020      1
94                           2/5/2020      1